package cn.itcast.tpms.domain;
// Generated Mar 17, 2018 9:36:51 AM by Hibernate Tools 4.0.0

/**
 * Manager generated by hbm2java
 */
public class Manager implements java.io.Serializable {

	private String mid;
	private String mname;
	private String mpassword;
	private String msex;
	private int mage;

	public Manager() {
	}

	public Manager(String mid, String mname, String mpassword, String msex, int mage) {
		this.mid = mid;
		this.mname = mname;
		this.mpassword = mpassword;
		this.msex = msex;
		this.mage = mage;
	}

	public String getMid() {
		return this.mid;
	}

	public void setMid(String mid) {
		this.mid = mid;
	}

	public String getMname() {
		return this.mname;
	}

	public void setMname(String mname) {
		this.mname = mname;
	}

	public String getMpassword() {
		return this.mpassword;
	}

	public void setMpassword(String mpassword) {
		this.mpassword = mpassword;
	}

	public String getMsex() {
		return this.msex;
	}

	public void setMsex(String msex) {
		this.msex = msex;
	}

	public int getMage() {
		return this.mage;
	}

	public void setMage(int mage) {
		this.mage = mage;
	}

}
