package cn.itcast.tpms.domain;
// Generated Mar 17, 2018 9:36:51 AM by Hibernate Tools 4.0.0

import java.util.Date;

import com.alibaba.fastjson.annotation.JSONField;

/**
 * Notice generated by hbm2java
 */
public class Notice implements java.io.Serializable {

	private String nid;
	private String ntext;
	@JSONField(format="yyyy-MM-dd")
	private Date ttime;
	private String ntitle;
	private String nauthor;

	public Notice() {
	}

	public Notice(String nid, String ntext, Date ttime, String ntitle, String nauthor) {
		this.nid = nid;
		this.ntext = ntext;
		this.ttime = ttime;
		this.ntitle = ntitle;
		this.nauthor = nauthor;
	}

	public String getNid() {
		return this.nid;
	}

	public void setNid(String nid) {
		this.nid = nid;
	}

	public String getNtext() {
		return this.ntext;
	}

	public void setNtext(String ntext) {
		this.ntext = ntext;
	}

	public Date getTtime() {
		return this.ttime;
	}

	public void setTtime(Date ttime) {
		this.ttime = ttime;
	}

	public String getNtitle() {
		return this.ntitle;
	}

	public void setNtitle(String ntitle) {
		this.ntitle = ntitle;
	}

	public String getNauthor() {
		return this.nauthor;
	}

	public void setNauthor(String nauthor) {
		this.nauthor = nauthor;
	}

}
