package cn.itcast.tpms.domain;
// Generated Mar 17, 2018 9:36:51 AM by Hibernate Tools 4.0.0

import java.util.Date;

import com.alibaba.fastjson.annotation.JSONField;

/**
 * Ticket generated by hbm2java
 */
public class Ticket implements java.io.Serializable {

	private String tid;
	private Traffic traffic;
	private DetialCat detialCat;
	@JSONField(format="yyyy-MM-dd HH-mm-ss")
	private Date ttime;
	private String tsite;
	private String tunlawfulAct;
	private int tscore;
	private Integer tfine;
	private String tstate;

	public Ticket() {
	}

	public Ticket(String tid, Traffic traffic, DetialCat detialCat, Date ttime, String tsite, String tunlawfulAct,
			int tscore, String tstate) {
		this.tid = tid;
		this.traffic = traffic;
		this.detialCat = detialCat;
		this.ttime = ttime;
		this.tsite = tsite;
		this.tunlawfulAct = tunlawfulAct;
		this.tscore = tscore;
		this.tstate = tstate;
	}

	public Ticket(String tid, Traffic traffic, DetialCat detialCat, Date ttime, String tsite, String tunlawfulAct,
			int tscore, Integer tfine, String tstate) {
		this.tid = tid;
		this.traffic = traffic;
		this.detialCat = detialCat;
		this.ttime = ttime;
		this.tsite = tsite;
		this.tunlawfulAct = tunlawfulAct;
		this.tscore = tscore;
		this.tfine = tfine;
		this.tstate = tstate;
	}

	public String getTid() {
		return this.tid;
	}

	public void setTid(String tid) {
		this.tid = tid;
	}

	public Traffic getTraffic() {
		return this.traffic;
	}

	public void setTraffic(Traffic traffic) {
		this.traffic = traffic;
	}

	public DetialCat getDetialCat() {
		return this.detialCat;
	}

	public void setDetialCat(DetialCat detialCat) {
		this.detialCat = detialCat;
	}

	public Date getTtime() {
		return this.ttime;
	}

	public void setTtime(Date ttime) {
		this.ttime = ttime;
	}

	public String getTsite() {
		return this.tsite;
	}

	public void setTsite(String tsite) {
		this.tsite = tsite;
	}

	public String getTunlawfulAct() {
		return this.tunlawfulAct;
	}

	public void setTunlawfulAct(String tunlawfulAct) {
		this.tunlawfulAct = tunlawfulAct;
	}

	public int getTscore() {
		return this.tscore;
	}

	public void setTscore(int tscore) {
		this.tscore = tscore;
	}

	public Integer getTfine() {
		return this.tfine;
	}

	public void setTfine(Integer tfine) {
		this.tfine = tfine;
	}

	public String getTstate() {
		return this.tstate;
	}

	public void setTstate(String tstate) {
		this.tstate = tstate;
	}

}
