package cn.itcast.tpms.domain;
// Generated Mar 17, 2018 9:36:51 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import com.alibaba.fastjson.annotation.JSONField;

/**
 * Traffic generated by hbm2java
 */
public class Traffic implements java.io.Serializable {

	private String pid;
	private String ppassword;
	private String pname;
	private String psex;
	private int page;
	private String ticket;
	private String ppic;
	@JSONField(serialize=false)
	private Set tickets = new HashSet(0);

	public Traffic() {
	}

	public Traffic(String pid, String ppassword, String pname, String psex, int page) {
		this.pid = pid;
		this.ppassword = ppassword;
		this.pname = pname;
		this.psex = psex;
		this.page = page;
	}

	public Traffic(String pid, String ppassword, String pname, String psex, int page, String ticket, String ppic,
			Set tickets) {
		this.pid = pid;
		this.ppassword = ppassword;
		this.pname = pname;
		this.psex = psex;
		this.page = page;
		this.ticket = ticket;
		this.ppic = ppic;
		this.tickets = tickets;
	}

	public String getPid() {
		return this.pid;
	}

	public void setPid(String pid) {
		this.pid = pid;
	}

	public String getPpassword() {
		return this.ppassword;
	}

	public void setPpassword(String ppassword) {
		this.ppassword = ppassword;
	}

	public String getPname() {
		return this.pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	public String getPsex() {
		return this.psex;
	}

	public void setPsex(String psex) {
		this.psex = psex;
	}

	public int getPage() {
		return this.page;
	}

	public void setPage(int page) {
		this.page = page;
	}

	public String getTicket() {
		return this.ticket;
	}

	public void setTicket(String ticket) {
		this.ticket = ticket;
	}

	public String getPpic() {
		return this.ppic;
	}

	public void setPpic(String ppic) {
		this.ppic = ppic;
	}

	public Set getTickets() {
		return this.tickets;
	}

	public void setTickets(Set tickets) {
		this.tickets = tickets;
	}

}
